let b = "ahoj";
console.log(b);
var a = 4;
var c  = 3;
var nasobek = a*c;
console.log("nasobek: "+nasobek);
var delitel = a/c;
console.log("delitel: "+delitel);
var plus = a+c;
console.log("soucet: "+plus);
var minus = a-c;
console.log("minus: "+minus);
var sin =   Math.sin(a)
console.log("sinus: "+sin);
var cos = Math.cos(a);
console.log("cosinus: "+cos);
var tan = Math.tan(a);
console.log("tangens: "+tan);
var cotan = Math.cos(a)/Math.sin(a);
console.log("cotangens: "+cotan);
var log = Math.log(a,b);
console.log("logaritmus: "+log);
var exp = Math.exp(a);
console.log("exponencial: "+exp);
var sqr = Math.sqrt(a);
console.log("square root: "+sqr);
