let b = "ahoj";
console.log(b);
var a = 4;
var c  = 3;
var nasobek = a*c;
console.log(nasobek);
var delitel = a/c;
console.log(delitel);
var plus = a+c;
console.log(plus);
var minus = a-c;
console.log(minus);
var sin =   Math.sin(a)
console.log(sin);
var cos = Math.cos(a);
console.log(cos);
var tan = Math.tan(a);
console.log(tan);
var cotan = Math.cos(a)/Math.sin(a);
console.log(cotan);
var log = Math.log(a,b);
console.log(log);
var exp = Math.exp(a);
console.log(exp);
var sqr = Math.sqrt(a);
console.log(sqr);
